server:
  port: 8080 # 서버 포트(기본값은 8080)
spring:
  profiles:
    active: dev # 기본적으로 dev 환경임을 명시
  thymeleaf:
    cache: false # 타임리프 캐시 끄기
    prefix: file:src/main/resources/templates/ # 타임리프 캐시 끄기(이 설정을 해야 꺼짐)
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    enabled: true
    suffix: .html
    template-resolver-order: 1
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create # DB 테이블 자동생성(엔티티 클래스만 만들면 됨)
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug